server:
  port: 8080

spring:
  application:
    name: fishhub-auth
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true

rate-limit:
  api:
    limit: 100 # 接口限流阈值

nacos:
  config: # Nacos 配置中心
    access-key: # 身份验证
    secret-key: # 身份验证
    data-id: fishhub-auth # 指定要加载的配置数据的 Data Id
    group: DEFAULT_GROUP # 指定配置数据所属的组
    type: yaml # 指定配置数据的格式
    server-addr: http://127.0.0.1:8848/ # 指定 Nacos 配置中心的服务器地址
    auto-refresh: true # 是否自动刷新配置
    remote-first: true # 是否优先使用远程配置
    bootstrap:
      enable: true # 启动时，预热配置
