server:
  port: 8080

spring:
  application:
    name: fishhub-auth
  profiles:
    active: dev

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: random-128
  is-log: true