<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>hk.ljx</groupId>
        <artifactId>fishhub-framework</artifactId>
        <version>${revision}</version>
    </parent>

    <packaging>jar</packaging>

    <artifactId>fishhub-spring-boot-starter-biz-id</artifactId>
    <name>${project.artifactId}</name>
    <description>分布式发号器 Starter 组件（高性能嵌入式雪花算法与双段号段）</description>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>hk.ljx</groupId>
            <artifactId>fishhub-common</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
        </dependency>
    </dependencies>
</project>
